services:
  nanobot-gateway:
    image: ${NANOBOT_IMAGE:-ghcr.io/Mlychen/nanobot:edge}
    container_name: nanobot-gateway
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18790:18790
    volumes:
      - ~/.nanobot:/home/nanobot/.nanobot
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M

  nanobot-api:
    image: ${NANOBOT_IMAGE:-ghcr.io/Mlychen/nanobot:edge}
    container_name: nanobot-api
    command:
      ["serve", "--host", "0.0.0.0", "-w", "/home/nanobot/.nanobot/api-workspace"]
    restart: unless-stopped
    ports:
      - 127.0.0.1:8900:8900
    volumes:
      - ~/.nanobot:/home/nanobot/.nanobot
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M

  nanobot-cli:
    image: ${NANOBOT_IMAGE:-ghcr.io/Mlychen/nanobot:edge}
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
    volumes:
      - ~/.nanobot:/home/nanobot/.nanobot
